### ISSUE TITLE
Why require an account?

### ISSUE THREAD

**Issue by swrobel** [fabriziobertoglio1987/surf-react-native#4]
I don't see what it accomplishes and you can't even try the app without it. Google login is nice but you probably want to properly set up the app name![image](https://user-images.githubusercontent.com/157270/82128431-0852d900-9770-11ea-8cee-17e8a0c0cad0.jpeg)

**Comment by fabOnReact** [comment]
I agree with you. There is no need for authentication. I will not build the authentication functionalities in the future.

I ll update the Google Project app name in my next release

Thanks a lot for the feedback 😃 
I wish you a good weekend
